### ISSUE TITLE
Need some help clearing PR's?

### ISSUE THREAD

**Issue by breakerh** [markodenic/web-development-resources#265]
If you're open to it I would love to help approving or declining (and providing feedback) on the merge requests.
If you don't want to give someone you don't know access or would like to maintain it yourself I fully understand!

Thank you for this list :)

**Comment by markodenic** [comment]
Hi, @breakerh. Sure! Can I DM you somewhere, so I can give you a few tips?

**Comment by breakerh** [comment]
Thanks! You can contact me on bram.h@fullstak.nl or bhammer93@gmail.com

Thanks!
Could you remove (or let me know) when you got the addresses. Then i can remove them :)

**Comment by breakerh** [comment]
ps. is it correct I didn't see any mail or DM? If you prefer other channels let me know!
Understand if you need to find the time to do so :)

**Comment by markodenic** [comment]
Hey, @breakerh!
Let's do this. :)
I added you as a collaborator. So, you basically have all permissions. 
Please read the [`contributing guidelines`](./CONTRIBUTING.md). I won't assign any PRs to you, just grab any when you have some time and merge them.
Please, leave PRs with new sections and YouTube channels to me. 
If you have any questions or doubts, you can write me on [Twitter](https://twitter.com/denicmarko).
Thank you!
