### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by hengage** [markodenic/web-development-resources#273]
There is a duplicate in the 'Youtube Channels' resource section. [Adrian Twarog](https://www.youtube.com/channel/UCvM5YYWwfLwpcQgbRr68JLQ) appears twice.

I would happy to correct it.

**Comment by Dighii** [comment]
Excellent observation skills you got there.

**Comment by anthonychinwe** [comment]
Nice observation, I'm working on it

**Comment by markodenic** [comment]
@anthonychinwe, thanks! Solved in https://github.com/markodenic/web-development-resources/pull/279.
