### ISSUE TITLE
Docker web dev environment

### ISSUE THREAD

**Issue by MizouziE** [markodenic/web-development-resources#290]
Hi, just wanted to ask. 

I know of and have always used a super easy to use docker recipe from a well maintained repository. Would that also be something worth adding to the list?

It has:
- Clear and concise documentation
- Pre built to support most projects that require php, node, mySQL, Redis, mailhog and even elasticsearch
- easily customizable per the needs of your project

I'd love to share it with people, especially those starting out because it was such a huge help for me at the beginning of my learning and still is to this day.

**Comment by breakerh** [comment]
It could be added under `other` i think?
You could create a PR i will leave it open for @markodenic to decide if he sees fit.

**Comment by markodenic** [comment]
Hey @MizouziE. We don't have a section for that.
