### ISSUE TITLE
Add a 'Stock videos' category

### ISSUE THREAD

**Issue by anthonychinwe** [markodenic/web-development-resources#361]
Consider adding a category for free stock videos and related resources.

**Comment by Brianabby** [comment]
Do you mean like a pixabay that provide free images, you want yours to be video under one category?

**Comment by anthonychinwe** [comment]
Yes, I wanted to add a resource like pixabay, and it offers only free stock video clips ( https://coverr.co/), but I wasn't sure if I should add it under the `Photos` category.

**Comment by prasad669** [comment]
yes i wanted to add resources related stock videos in  your project could you please give us opportunity to make it 
better

**Comment by breakerh** [comment]
@markodenic not a bad idea right? Can I add that category? Or is there a reason we don't have it?

**Comment by markodenic** [comment]
@breakerh Sure, you can add it. Thanks!

**Comment by siddhant7666** [comment]
@anthonychinwe @markodenic If this issue is not yet resolved, can you please assign this to me. I am a beginner in Open source world, and I am trying to figure out how things work. I can add a category for free stock videos and related resources in it as well. And it would be of great help if you can label this with hacktoberfest.

**Comment by markodenic** [comment]
@siddhant7666 Done! Thanks!

**Comment by siddhant7666** [comment]
@markodenic I have _successfully resolved_ the issue and made a PR. Please suggest me if some changes are needed there, and alongwith it I have made you a **request** of **labeling** the issue with **hacktoberfest** and **hactoberfest-accepted**

**Comment by breakerh** [comment]
Thank you for doing so @siddhant7666 !
Seems like I've totally missed the assignment. Sorry.

**Comment by siddhant7666** [comment]
Ahh.....no worries @breakerh Sir.

**Comment by siddhant7666** [comment]
@breakerh Sir can you please label that pr with  **hacktoberfest** and **hactoberfest-accepted**. It will be of great help to me.
As I have participated in Biggest Open Source Festival and we have to make 4 successfull PRs
Thanks

**Comment by devharshu** [comment]
Hey, can you assign this to me?

**Comment by siddhant7666** [comment]
Hello @devharshu , this issue has been resolved already.
If you want to contribute to the repo then keep looking for the new issue or you can raise an issue too.
Thanks

**Comment by devharshu** [comment]
Okay, Thanks @siddhant7666
