### ISSUE TITLE
Web development

### ISSUE THREAD

**Issue by Krishna25-12** [markodenic/web-development-resources#412]

**Comment by breakerh** [comment]
Hello @Krishna25-12 
Can I help you since you've opened an empty issue?

**Comment by IsPhenyo24** [comment]
Let's create something useful like an website that can book artist and entertainment stuff

**Comment by KarimDouadjia** [comment]
yeah i like the idea

**Comment by IsPhenyo24** [comment]
But am still a beginner looking forward to learn more about html, css and JavaScript so we can be able to make a responsive site I can structure the document but I can't make it responsive thts the issue with me

**Comment by KarimDouadjia** [comment]
we are the same you contact me to learn togothere  and help each other

**Comment by IsPhenyo24** [comment]
How mind if u send me ur what's app link so I can be able to contact you
