### ISSUE TITLE
New category: Sustainability

### ISSUE THREAD

**Issue by ChrisButterworth** [markodenic/web-development-resources#641]
As the creator of [Beacon](https://digitalbeacon.co), it'd be brilliant to see more information about sustainability within these resources.

Happy to put a list together and add them but thought I'd check to make sure there's some demand for it first.

**Comment by markodenic** [comment]
@ChrisButterworth, I'm a fan of the Beacon. Thank you for your efforts.
I like the idea and it would be great if you could help out. 
Happy to see the list when it's ready. Thanks!
